use crate::utils::{Year, UNIMPLEMENTED_DAY};

pub mod day_01;

pub static YEAR: Year = Year {
    year: 2022,
    days: [
        day_01::DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
        UNIMPLEMENTED_DAY,
    ],
};
